In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
print('shape- ',a.shape)
print('dim- ',a.ndim)

shape-  (3, 5)
dim-  2


In [10]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.arange(6) 

array([0, 1, 2, 3, 4, 5])

In [13]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
c

array([20, 29, 38, 47])

In [14]:
b**2

array([0, 1, 4, 9])

In [27]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [29]:
an_array = np.where(a % 2 == 0, 55,a)
an_array

array([ 55,   1,  55,  27,  55, 125,  55, 343,  55, 729])

In [16]:
a[2:5]

array([ 8, 27, 64])

In [19]:
from tempfile import TemporaryFile
outfile = TemporaryFile()
np.save('test.npy', a)

In [20]:
xx = np.load('test.npy')
xx

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [21]:
with open('test2.npy', 'wb') as f:
    np.save(f, np.array([1, 2]))
    np.save(f, np.array([1, 3]))
with open('test2.npy', 'rb') as f:
    a = np.load(f)
    b = np.load(f)
print(a, b)

[1 2] [1 3]
